---
site_name: Ubuntu Virtual Machine
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Ubuntu Virtual Machine for sommerfeld.io projects.

repo_name: sommerfeld-io/vm-ubuntu
repo_url: https://github.com/sommerfeld-io/vm-ubuntu

copyright: Copyright &copy; 2024 Sommerfeld.io

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.code.copy
    - content.tabs.link
    # - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
      ServerURL: http://localhost:3888
  # - search:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/vm-ubuntu

nav:
  - Getting Started: index.md
  - portainer.md
  - minikube.md
  - About this project:
      - about/contribute.md
      - about/security.md
      - about/code-of-conduct.md
      - about/license.md
